
export const LOADING_PATIENTS = 'LOADING_PATIENTS'
export const GET_PATIENTS = 'GET_PATIENTS'
export const GET_PATIENT = 'GET_PATIENT'

export const GET_PATIENTVS = 'GET_PATIENTVS'

export const PUT_PATIENT = 'PUT_PATIENT'
export const PUT_PATIENTVS = 'PUT_PATIENTVS'

export const POST_PATIENT = 'POST_PATIENT'
export const POST_PATIENTVS = 'POST_PATIENTVS'

export const DELETE_PATIENT = 'DELETE_PATIENT'
export const DELETE_PATIENTVS = 'DELETE_PATIENTVS'